
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccelerationUnit", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/ConvertAcceleration.asmx?WSDL")
public class AccelerationUnit
    extends Service
{

    private final static URL ACCELERATIONUNIT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.webservicex.AccelerationUnit.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.webservicex.AccelerationUnit.class.getResource(".");
            url = new URL(baseUrl, "http://www.webservicex.net/ConvertAcceleration.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.webservicex.net/ConvertAcceleration.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCELERATIONUNIT_WSDL_LOCATION = url;
    }

    public AccelerationUnit(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccelerationUnit() {
        super(ACCELERATIONUNIT_WSDL_LOCATION, new QName("http://www.webserviceX.NET/", "AccelerationUnit"));
    }

    /**
     * 
     * @return
     *     returns AccelerationUnitSoap
     */
    @WebEndpoint(name = "AccelerationUnitSoap")
    public AccelerationUnitSoap getAccelerationUnitSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "AccelerationUnitSoap"), AccelerationUnitSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccelerationUnitSoap
     */
    @WebEndpoint(name = "AccelerationUnitSoap")
    public AccelerationUnitSoap getAccelerationUnitSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "AccelerationUnitSoap"), AccelerationUnitSoap.class, features);
    }

}
